# Generated by Django 2.2.7 on 2019-12-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arcticle_preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Arcticle',
        ),
    ]
