# Generated by Django 2.2.7 on 2019-12-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0002_auto_20191212_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcticle_preview',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
