# Generated by Django 2.2.7 on 2019-12-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0003_arcticle_preview_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcticle_preview',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
