# Generated by Django 2.2.7 on 2019-12-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0004_auto_20191215_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcticle_preview',
            name='genre',
            field=models.ManyToManyField(to='base_module.Genre'),
        ),
    ]
