# Generated by Django 2.2.7 on 2019-12-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_module.Arcticle_Preview'),
        ),
    ]
