# Generated by Django 2.2.7 on 2019-12-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0007_auto_20191219_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.ManyToManyField(to='base_module.Genre'),
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Arcticle_preview',
        ),
    ]
