# Generated by Django 2.2.7 on 2019-12-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0010_auto_20191224_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='developer',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
