# Generated by Django 2.2.7 on 2019-12-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0011_article_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='interface_language',
            field=models.ManyToManyField(related_name='Интерфейс', to='base_module.Language'),
        ),
        migrations.AddField(
            model_name='article',
            name='voice_language',
            field=models.ManyToManyField(related_name='Озвучка', to='base_module.Language'),
        ),
    ]
