# Generated by Django 2.2.7 on 2019-12-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0012_auto_20191230_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='release_date',
            field=models.IntegerField(max_length=4),
        ),
    ]
