# Generated by Django 2.2.7 on 2020-01-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0018_auto_20200101_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scr',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='scr2',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='scr3',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='scr4',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
