# Generated by Django 2.2.7 on 2020-01-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0019_auto_20200104_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='RePack_by',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
