# Generated by Django 2.2.7 on 2020-01-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0020_auto_20200105_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='weight',
            field=models.CharField(max_length=50),
        ),
    ]
