# Generated by Django 2.2.7 on 2020-01-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0021_auto_20200105_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='torrent',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
