# Generated by Django 3.0.2 on 2020-01-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_module', '0023_article_gameplay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='releasse_date',
            new_name='release_date',
        ),
    ]
